//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmCentral
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string StockID { get; set; }
        public string ProductID { get; set; }
        public int StockAmount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
